package main.java.br.edu.ifpb.gui;



import main.java.br.edu.ifpb.domain.Contato;
import javax.swing.*;


// public class MainWindow {
//     private final JFrame frame;
//     private final JList<Contato> list;
//     private final JPopupMenu menu;

//     public MainWindow(){
//         frame = new JFrame("Agenda de contatos");
//         list = new JList<>();
//         menu = new JPopupMenu();
//     }

//     public void show() {
//         frame.setSize(400, 300);
//         frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
//         frame.setLocationRelativeTo(null);
//         frame.setVisible(true);
//     }

//     public static void main(String[] args) {
//         MainWindow main = new MainWindow();
//         main.show();
//     }

// }


// public class MainWindow extends javax.swing.JFrame {

//     /**
//      * Creates new form MainWindow
//      */
//     public MainWindow() {
//         initComponents();
//     }

//     /**
//      * This method is called from within the constructor to initialize the form.
//      * WARNING: Do NOT modify this code. The content of this method is always
//      * regenerated by the Form Editor.
//      */
//     @SuppressWarnings("unchecked")
//     // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
//     private void initComponents() {

//         jLabel1 = new javax.swing.JLabel();
//         jSeparator1 = new javax.swing.JSeparator();
//         jButton1 = new javax.swing.JButton();

//         setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//         setBackground(new java.awt.Color(255, 255, 255));

//         jLabel1.setFont(new java.awt.Font("Noto Sans CJK HK", 1, 18)); // NOI18N
//         jLabel1.setForeground(new java.awt.Color(0, 153, 0));
//         jLabel1.setText("Agenda de Contatos");

//         jSeparator1.setForeground(new java.awt.Color(0, 153, 0));

//         jButton1.setBackground(new java.awt.Color(0, 153, 0));
//         jButton1.setText("Adicionar \nnovo contato");

//         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//         getContentPane().setLayout(layout);
//         layout.setHorizontalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addContainerGap(205, Short.MAX_VALUE))
//             .addComponent(jSeparator1)
//             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                 .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addGap(75, 75, 75))
//         );
//         layout.setVerticalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                 .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
//                 .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addContainerGap())
//         );

//         pack();
//     }// </editor-fold>                        

//     /**
//      * @param args the command line arguments
//      */
//     public static void main(String args[]) {
//         /* Set the Nimbus look and feel */
//         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//         /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//          * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//          */
//         try {
//             for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                 if ("Nimbus".equals(info.getName())) {
//                     javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                     break;
//                 }
//             }
//         } catch (ClassNotFoundException ex) {
//             java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//         } catch (InstantiationException ex) {
//             java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//         } catch (IllegalAccessException ex) {
//             java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//         } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//             java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//         }
//         //</editor-fold>

//         /* Create and display the form */
//         java.awt.EventQueue.invokeLater(new Runnable() {
//             public void run() {
//                 new MainWindow().setVisible(true);
//             }
//         });
//     }

//     // Variables declaration - do not modify                     
//     private javax.swing.JButton jButton1;
//     private javax.swing.JLabel jLabel1;
//     private javax.swing.JSeparator jSeparator1;
//     // End of variables declaration                   
// }


// import java.awt.*;
// import java.awt.event.ActionEvent;
// import java.awt.event.ActionListener;

// // Classe principal que representa a janela principal
// public class MainWindow extends JFrame {

//     // Construtor da classe
//     public MainWindow() {
//         // Configurações básicas da janela
//         setTitle("Interface Linda");
//         setSize(400, 300);
//         setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//         setLocationRelativeTo(null); // Centraliza a janela na tela

//         // Cria um painel para conter os componentes
//         JPanel panel = new JPanel();
//         panel.setLayout(new FlowLayout());

//         // Cria um botão
//         JButton button = new JButton("Clique-me!");

//         // Adiciona um ouvinte de ação ao botão
//         button.addActionListener(new ActionListener() {
//             @Override
//             public void actionPerformed(ActionEvent e) {
//                 // Ação a ser realizada quando o botão for clicado
//                 JOptionPane.showMessageDialog(MainWindow.this, "Você clicou no botão! Linda, não é?");
//             }
//         });

//         // Adiciona o botão ao painel
//         panel.add(button);

//         // Adiciona o painel à janela
//         add(panel);

//         // Torna a janela visível
//         setVisible(true);
//     }

//     // Método principal para iniciar o aplicativo
//     public static void main(String[] args) {
//         // Cria uma instância da classe MainWindow
//         SwingUtilities.invokeLater(new Runnable() {
//             @Override
//             public void run() {
//                 new MainWindow();
//             }
//         });
//     }
// }


// public class MainWindow extends javax.swing.JFrame {
//     private ImagePanel imagePanel;


//     /**
//      * Creates new form MainWindow
//      */
//     public MainWindow() {
//         imagePanel = new ImagePanel("Blue wallpaper.png");
//         setContentPane(imagePanel);
//         initComponents();
//     }

//     /**
//      * This method is called from within the constructor to initialize the form.
//      * WARNING: Do NOT modify this code. The content of this method is always
//      * regenerated by the Form Editor.
//      */
//     @SuppressWarnings("unchecked")
//     // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
//     private void initComponents() {

//         jLabel1 = new javax.swing.JLabel();
//         jLabel2 = new javax.swing.JLabel();
//         jLabel3 = new javax.swing.JLabel();
//         jLabel4 = new javax.swing.JLabel();
//         jScrollPane1 = new javax.swing.JScrollPane();
//         jList1 = new javax.swing.JList<>();
//         jButton1 = new javax.swing.JButton();
//         jButton2 = new javax.swing.JButton();
//         jLabel5 = new javax.swing.JLabel();

//         jLabel1.setText("jLabel1");

//         jLabel2.setText("jLabel2");

//         setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//         setTitle("Agenda de Contatos");
//         setMaximumSize(new java.awt.Dimension(500, 300));
//         setMinimumSize(new java.awt.Dimension(500, 300));
//         setPreferredSize(new java.awt.Dimension(500, 300));
//         getContentPane().setLayout(null);
//         getContentPane().add(jLabel3);
//         jLabel3.setBounds(120, 323, 0, 0);

//         jLabel4.setFont(new java.awt.Font("Noto Sans CJK JP", 1, 18)); // NOI18N
//         jLabel4.setForeground(new java.awt.Color(33, 50, 78));
//         jLabel4.setText("Agenda de Contatos");
//         getContentPane().add(jLabel4);
//         jLabel4.setBounds(10, 10, 190, 30);

//         jScrollPane1.setBackground(new java.awt.Color(242, 242, 242));

//         jList1.setBackground(new java.awt.Color(170, 213, 248));
//         jList1.setBorder(null);
//         jList1.setFont(new java.awt.Font("Noto Sans CJK HK", 1, 14)); // NOI18N
//         jList1.setForeground(new java.awt.Color(33, 50, 78));
//         jList1.setModel(new javax.swing.AbstractListModel<String>() {
//             String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 5", "Item 5", "Item 5" };
//             public int getSize() { return strings.length; }
//             public String getElementAt(int i) { return strings[i]; }
//         });
//         jScrollPane1.setViewportView(jList1);

//         getContentPane().add(jScrollPane1);
//         jScrollPane1.setBounds(10, 50, 260, 170);

//         jButton1.setBackground(new java.awt.Color(33, 50, 78));
//         jButton1.setFont(new java.awt.Font("Noto Sans CJK HK", 1, 12)); // NOI18N
//         jButton1.setForeground(new java.awt.Color(255, 255, 255));
//         jButton1.setText("Adicionar");
//         jButton1.setBorder(null);
//         getContentPane().add(jButton1);
//         jButton1.setBounds(350, 50, 100, 35);

//         jButton2.setBackground(new java.awt.Color(33, 50, 78));
//         jButton2.setFont(new java.awt.Font("Noto Sans CJK HK", 1, 12)); // NOI18N
//         jButton2.setForeground(new java.awt.Color(255, 255, 255));
//         jButton2.setText("Editar");
//         jButton2.setBorder(null);
//         getContentPane().add(jButton2);
//         jButton2.setBounds(350, 85, 100, 35);

//         jButton2.setBackground(new java.awt.Color(33, 50, 78));
//         jButton2.setFont(new java.awt.Font("Noto Sans CJK HK", 1, 12)); // NOI18N
//         jButton2.setForeground(new java.awt.Color(255, 255, 255));
//         jButton2.setText("Editar");
//         jButton2.setBorder(null);
//         getContentPane().add(jButton2);
//         jButton2.setBounds(350, 85, 100, 35);

//         // jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("Blue wallpaper.jpeg"))); // NOI18N
//         // jLabel5.setText("        ");
//         // jLabel5.setMaximumSize(new java.awt.Dimension(500, 300));
//         // jLabel5.setMinimumSize(new java.awt.Dimension(500, 300));
//         // getContentPane().add(jLabel5);
//         // jLabel5.setBounds(0, 0, 500, 300);

        

//         pack();
//     }// </editor-fold>                        

//     /**
//      * @param args the command line arguments
//      */
//     public static void main(String args[]) {
//         /* Set the Nimbus look and feel */
//         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//         /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//          * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//          */
//         try {
//             for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                 if ("Nimbus".equals(info.getName())) {
//                     javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                     break;
//                 }
//             }
//         } catch (ClassNotFoundException ex) {
//             java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//         } catch (InstantiationException ex) {
//             java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//         } catch (IllegalAccessException ex) {
//             java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//         } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//             java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//         }
//         //</editor-fold>

//         /* Create and display the form */
//         java.awt.EventQueue.invokeLater(new Runnable() {
//             public void run() {
//                 new MainWindow().setVisible(true);
//             }
//         });
//     }

//     // Variables declaration - do not modify                     
//     private javax.swing.JButton jButton1;
//     private javax.swing.JButton jButton2;
//     private javax.swing.JLabel jLabel1;
//     private javax.swing.JLabel jLabel2;
//     private javax.swing.JLabel jLabel3;
//     private javax.swing.JLabel jLabel4;
//     private javax.swing.JLabel jLabel5;
//     private javax.swing.JList<String> jList1;
//     private javax.swing.JScrollPane jScrollPane1;
//     // End of variables declaration                   
// }




public class MainWindow extends javax.swing.JFrame {
        private ImagePanel imagePanel;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        imagePanel = new ImagePanel("Blue wallpaper.png");
        setContentPane(imagePanel);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 300));
        setMinimumSize(new java.awt.Dimension(500, 300));
        setPreferredSize(new java.awt.Dimension(500,300));
        setTitle("Agenda de Contatos");

        jLabel1.setFont(new java.awt.Font("Noto Sans CJK HK", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 50, 78));
        jLabel1.setText("Agenda de Contatos");

        jTextField1.setFont(new java.awt.Font("Noto Sans CJK HK", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(33, 50, 78));
        jTextField1.setText("Buscar contato");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jList1.setBackground(new java.awt.Color(170, 213, 248));
        jList1.setFont(new java.awt.Font("Noto Sans CJK HK", 1, 14)); // NOI18N
        jList1.setForeground(new java.awt.Color(33, 50, 78));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setBackground(new java.awt.Color(33, 50, 78));
        jButton1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Excluir");

        jLabel2.setFont(new java.awt.Font("Noto Sans CJK HK", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(33, 50, 78));
        jLabel2.setText("Adicionar em:");

        jButton2.setBackground(new java.awt.Color(33, 50, 78));
        jButton2.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Editar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1)
                        .addGap(83, 83, 83))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(67, 67, 67)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainWindow mainWindow = new MainWindow();
                mainWindow.setVisible(true);
                mainWindow.setLocationRelativeTo(null); 
                
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}
